[task]
mode = "infer"
train_only=false
debug = true

# [trainer]
# loss_weight = 20
# epochs = 100
# train_batch_size = 16
# val_batch_size = 16

[model]
no_of_filters = 128
edge_extracts = [3]
num_blocks = 2
name = "ftnet"
pretrained_base = false
backbone = "resnext50_32x4d"
dilation = false

[dataset]
name = "mfn"
# dataset_path = "/mnt/C26EDFBB6EDFA687/lab-work/FTNet/data/processed_dataset/"
dataset_path='/mnt/C26EDFBB6EDFA687/lab-work/FTNet/data/processed_dataset/mfn/image/train/'


[checkpoint]
# resume = none
# pretrain_checkpoint =
save_dir = './results/infer'
test_checkpoint = "/mnt/C26EDFBB6EDFA687/lab-work/FTNet/Trained_Models/ftnet_resnext50_32x4d_filters_128_edge_3_blocks_2/rev-2/MFN Dataset/ckpt/val_mIOU=0.4121.ckpt"
save_images = true
save_images_as_subplots = true

[compute]
devices = 1
num_nodes = 1
accelerator = "auto"
strategy = "auto"
seed = 0
workers = 16
