[task]
mode = "train"
train_only=true
debug = true

[trainer]
loss_weight = 20
epochs = 1
train_batch_size = 1
val_batch_size = 1

[model]
no_of_filters = 128
edge_extracts = [3]
num_blocks = 2
name = "ftnet"
pretrained_base = true
backbone = "resnext50_32x4d"
dilation = false

[dataset]
name = "cityscapes_thermal_combine"
dataset_path='./data/processed_dataset/cityscape'
base_size = [[520,520]]
crop_size = [[480,480]]


[optimizer]
name = "SGD"
lr = 0.01
momentum = 0.9
weight_decay = 0.0001
beta1 = 0.9
beta2 = 0.999
epsilon = 1e-8

[scheduler]
name = "poly_warmstartup"
warmup_iters = 0
warmup_factor = 0.3333
warmup_method = "linear"

[checkpoint]
# resume = none
# pretrain_checkpoint = "/mnt/C26EDFBB6EDFA687/lab-work/FTNet/ftnet_models/val_mIOU=0.6403.ckpt"
save_dir = './results/'
test_checkpoint = '/mnt/C26EDFBB6EDFA687/lab-work/FTNet/ftnet_models/ftnet_resnext50_32x4d_filters_128_edge_3_blocks_2/rev-2/SCUTSEG Dataset/ckpt/val_mIOU=0.6711.ckpt'
save_images = true
save_images_as_subplots = false

[compute]
devices = 1
num_nodes = 1
accelerator = "auto"
strategy = "auto"
seed = 0
workers = 0
