[task]
mode = "train"
train_only=false
debug = false

[trainer]
loss_weight = 20
epochs = 100
train_batch_size = 16
val_batch_size = 16

[model]
no_of_filters = 128
edge_extracts = [3]
num_blocks = 2
name = "ftnet"
pretrained_base = true
backbone = "resnext50_32x4d"
dilation = false

[dataset]
name = "scutseg"
# dataset_path = "/mnt/C26EDFBB6EDFA687/lab-work/FTNet/data/processed_dataset/"
dataset_path='/mnt/C26EDFBB6EDFA687/lab-work/FTNet/data/processed_dataset/scutseg'
base_size = [[520,520]]
crop_size = [[480,480]]


[optimizer]
name = "SGD"
lr = 0.01
momentum = 0.9
weight_decay = 0.0001
beta1 = 0.9
beta2 = 0.999
epsilon = 1e-8

[scheduler]
name = "poly_warmstartup"
warmup_iters = 0
warmup_factor = 0.3333
warmup_method = "linear"

[checkpoint]
# resume = none
# pretrain_checkpoint =
save_dir = './results/scutseg'
# test_checkpoint =
save_images = true
save_images_as_subplots = true

[compute]
devices = 1
num_nodes = 1
accelerator = "auto"
strategy = "auto"
seed = 0
workers = 16
